version: "2"
volumes:
  data-jenkins:
    driver: "local"
services:
  jenkins:
    image: "jenkins:latest"
    ports:
      - "49001:8081"
    restart: "always"
    volumes:
      - "data-jenkins:/var/jenkins_home"