version: "2"
volumes:
  data-jenkins:
    driver: "local"
services:
  jenkins:
    build: .
    ports:
      - "49001:8080"
    restart: "always"
    volumes:
      - "data-jenkins:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    privileged: true